version: '3.1'

services:
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./reverse-proxy/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: Asia/Tokyo
    command: /bin/bash -c "envsubst '' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - gitlab
      - redmine
      - nexus
      - jenkins
      - archiva
    links:
      - gitlab
      - redmine
      - nexus
      - jenkins
      - archiva

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: localhost:80
    volumes:
      - gitlab-etc:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    ports:
      - '10081:10081'
      - '10080:80'
      - '10082:10082'
      - '10443:443'
      - '10022:22'
    environment:
      TZ: Asia/Tokyo
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['lfs_enabled'] = true
        external_url 'http://localhost:80/gitlab'
        mattermost_external_url 'http://localhost:10081'
        registry_external_url 'http://localhost:10082'
    links:
      - gitlab-runner
      - gitlab-specific-runner
      - nexus

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - gitlab-runner-etc:/etc/gitlab-runner
      - gitlab-runner-home:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.soc
    environment:
      TZ: Asia/Tokyo

  gitlab-specific-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - gitlab-specific-runner-etc:/etc/gitlab-runner
      - gitlab-specific-runner-home:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.soc
    environment:
      TZ: Asia/Tokyo

  redmine:
    image: redmine:latest
    restart: always
    ports:
      - '23000:3000'
    volumes:
      - redmine-files:/usr/src/redmine/files
      - ./redmine/config.ru:/usr/src/redmine/config.ru #nginx用
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: example
      RAILS_RELATIVE_URL_ROOT: /redmine
    links:
      - gitlab

  redmine-db:
    image: mysql:5.7
    restart: always
    volumes:
      - redmine-db-data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine

  nexus:
    image: sonatype/nexus3:latest
    restart: always
    ports:
      - '48081:8081'
    volumes:
      - nexus-data:/nexus-data
      - ./nexus/nexus.properties:/nexus-data/etc/nexus.properties #nginx用
      - ./nexus/jetty-http.xml:/opt/sonatype/nexus/etc/jetty-http.xml #nginx用
    environment:
      TZ: Asia/Tokyo
      NEXUS_CONTEXT: nexus #nginx用
 
  jenkins:
    image: jenkins:latest
    restart: always
    volumes:
      - jenkins-home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --prefix=/jenkins #nginx用
      TZ: Asia/Tokyo
    ports:
      - '58080:8080'
      - '50000:50000'
    links:
      - gitlab
      - nexus

  archiva:
    image: xetusoss/archiva
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - archiva-data:/archiva-data
      - ./archiva/archiva.xml:/archiva/contexts/archiva.xml #nginx用
    ports:
      - '1080:8080'

volumes:
  gitlab-etc:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-etc:
  gitlab-runner-home:
  gitlab-specific-runner-etc:
  gitlab-specific-runner-home:
  redmine-files:
  redmine-db-data:
  nexus-data:
  jenkins-home:
  archiva-data:

