version: '3.1'

services:
  elasticsearch:
    build: ./elk/es
    env_file:
      - ./common/common.env
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data/
      - ./elk/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elk/es/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    networks:
      - elk-nw

  kibana:
    build: ./elk/kibana
    env_file:
      - ./common/common.env
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    links:
      - elasticsearch:elasticsearch
    networks:
      - public
      - elk-nw

  logstash:
    build: ./elk/logstash
    env_file:
      - ./common/common.env
    volumes:
      - ./elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    links:
      - elasticsearch:elasticsearch
    networks:
      - elk-nw

networks:
  public:
  elk-nw:

volumes:
  es-data:
