version: '3.6'

services:
  nginx:
    image: nginx:latest
    env_file:
      - ./common/common.env
    restart: always
    volumes:
      - ./nginx/config/mysite.template:/etc/nginx/conf.d/mysite.template:ro
    ports:
      - '80:80'
      - '443:443'
    command: /bin/bash -c "envsubst '' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - gitlab
      - plantuml
    networks:
      - public

  gitlab:
    image: gitlab/gitlab-ce:latest
    env_file:
      - ./common/common.env
    restart: always
    volumes:
      - /mnt/home/gitlab/opt:/var/opt/gitlab
      - /mnt/home/gitlab/etc:/etc/gitlab
      - /mnt/home/gitlab/log:/var/log/gitlab
      - ./gitlab/_backup:/secret/gitlab/backups
      - ./gitlab/ce/config/omnibus_config.rb:/omnibus_config.rb:ro
    ports:
      - '10081:10081'
      - '10080:80'
      - '10082:10082'
      - '10443:443'
      - '10022:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    # configs:
    #   - source: gitlab
    #     target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    networks:
      - public
      - gitlab-nw

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    env_file:
      - ./common/common.env
    restart: always
    volumes:
      - /mnt/home/gitlab-runner/etc:/etc/gitlab-runner
      - /mng/home/gitlab-runner/home:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gitlab-nw

  plantuml:
    image : plantuml/plantuml-server:latest
    env_file:
      - ./common/common.env
    restart: always
    ports:
      - '38080:8080'
    volumes:
      - ./gitlab/plantuml/config/ROOT.xml:/var/lib/jetty/webapps/ROOT.xml:ro
    networks:
      - public
      - gitlab-nw

# configs:
#    gitlab:
#      file: ./gitlab/ce/config/omnibus_config.rb

secrets:
   gitlab_root_password:
     file: ./secrets/gitlab.txt

networks:
  public:
  gitlab-nw:
