version: '3.1'

services:
  ntp:
    build: ./ntp
    restart: always
    ports:
      - '123:123'
    networks:
      - public

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template:ro
    ports:
      - '80:80'
      - '443:443'
    command: /bin/bash -c "envsubst '' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - archiva
      - gitlab
      - jenkins
      - ntp
      - redmine
    networks:
      - public

  gitlab:
    build: ./gitlab/ce
    restart: always
    volumes:
      - gitlab-etc:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - ./gitlab/_backup:/secret/gitlab/backups
    ports:
      - '10081:10081'
      - '10080:80'
      - '10082:10082'
      - '10443:443'
      - '10022:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['lfs_enabled'] = true
        external_url 'http://localhost:80/gitlab'
        mattermost_external_url 'http://localhost:10081'
        registry_external_url 'http://localhost:10082'
    networks:
      - public
      - gitlab-nw

  gitlab-runner:
    build: ./gitlab/runner
    restart: always
    volumes:
      - gitlab-runner-etc:/etc/gitlab-runner
      - gitlab-runner-home:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.soc:ro
    networks:
      - gitlab-nw

  gitlab-specific-runner:
    build: ./gitlab/runner
    restart: always
    volumes:
      - gitlab-specific-runner-etc:/etc/gitlab-runner
      - gitlab-specific-runner-home:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.soc:ro
    networks:
      - gitlab-nw

  plantuml:
    build: ./gitlab/plantuml
    restart: always
    ports:
      - '38080:8080'
    networks:
      - gitlab-nw

  redmine:
    build: ./redmine/app
    restart: always
    ports:
      - '23000:3000'
    volumes:
      - redmine-files:/usr/src/redmine/files
      - ./redmine/config.ru:/usr/src/redmine/config.ru:ro #for nginx
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: example
      RAILS_RELATIVE_URL_ROOT: /redmine
    networks:
      - public
      - redmine-nw

  redmine-db:
    build: ./redmine/db
    restart: always
    volumes:
      - redmine-db-data:/var/lib/mysql
      - ./redmine/db/charset.cnf:/etc/mysql/conf.d/charset.cnf/:ro #for japanese
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    networks:
      - redmine-nw

  nexus:
    build: ./nexus
    restart: always
    ports:
      - '48081:8081'  #others
      - '48082:48082' #docker
    volumes:
      - nexus-data:/nexus-data
      # https://help.sonatype.com/repomanager3/backup-and-restore
      - nexus-backup:/nexus-backup #for config backup
      #- nexus-backup:/restore-from-backup:ro #for config restore
      - ./nexus/nexus.properties:/nexus-data/etc/nexus.properties:ro #for nginx
    environment:
      NEXUS_CONTEXT: nexus #for nginx
    networks:
      - public


  jenkins:
    build: ./jenkins/master
    restart: always
    volumes:
      - jenkins-home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --prefix=/jenkins #for nginx
    ports:
      - '58080:8080'
      - '50000:50000'
    networks:
      - public
      - jenkins-nw

  archiva:
    build: ./archiva
    restart: always
    volumes:
      - archiva-data:/archiva-data
      - ./archiva/archiva.xml:/archiva/contexts/archiva.xml:ro #for nginx
    ports:
      - '1080:8080'
    networks:
      - public

  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
      ROCKETCHAT_URL: rocketchat:3000
      ROCKETCHAT_ROOM: GENERAL
      ROCKETCHAT_USER: bot
      ROCKETCHAT_PASSWORD: bot
      BOT_NAME: bot
      EXTERNAL_SCRIPTS: hubot-pugme,hubot-help
    networks:
      - gitlab-nw

  elasticsearch:
    build: ./elk/es
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data/
      - ./elk/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elk/es/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    networks:
      - elk-nw

  kibana:
    build: ./elk/kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    links:
      - elasticsearch:elasticsearch
    networks:
      - elk-nw

  samba:
    build: ./samba
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
      - samba-data:/share
    ports:
      - "445:445"
    networks:
      - public

networks:
  elk-nw:
  gitlab-nw:
  jenkins-nw:
  public:
  redmine-nw:

volumes:
  archiva-data:
  es-data:
  gitlab-data:
  gitlab-etc:
  gitlab-logs:
  gitlab-runner-etc:
  gitlab-runner-home:
  gitlab-specific-runner-etc:
  gitlab-specific-runner-home:
  jenkins-home:
  nexus-backup:
  nexus-data:
  redmine-db-data:
  redmine-files:
  samba-data:
